version: '2'
services:
  tree:
    build:
      context: ./
      dockerfile: Dockerfile
    image: tree
    volumes:
      - ./sample/tree.json:/usr/src/tree-app/sample/tree.json
    ports:
      - 8887:8887
    networks:
      - tree-network
networks:
  tree-network: