FROM maven:3.6.3-jdk-11-slim
WORKDIR /usr/src/Tree
COPY . /usr/src/Tree/
RUN mvn package
WORKDIR /usr/src/tree-app
RUN cp /usr/src/Tree/target/*.jar ./app.jar
EXPOSE 8888
CMD ["java", "-jar","app.jar"]