spring:
  application:
    name: Tree

server:
  port: 8888
  compression:
    enabled: true
    mime-types: ['application/json', 'text/xml']
  servlet:
    application-display-name: 'tree'
  undertow:
    ioThreads: 32
    workerThreads: 256
    direct-buffers: true
    accesslog:
      enabled: true
      prefix: access
      suffix: log
      dir: logs
      pattern: common